# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
  form_themes:
    - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
fos_ck_editor:
  input_sync: true
  default_config: admin_config
  configs:
    admin_config:
      toolbar: "full"
#      toolbar: "standard"
      toolbarCanCollapse: true
      skin: "prestige,/admin/prestige/"
  toolbars:
    configs:
      admin_toolbar: [ [ "Source", "-", "Save" ], "/", [ "Anchor" ], "/", [ "Maximize" ] ]
