vich_uploader:
  db_driver: orm
  metadata:
    type: attribute
  mappings:
    event:
      uri_prefix: /uploads/images/event
      upload_destination: '%kernel.project_dir%/public/uploads/images/event'
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
      namer:
        service: Vich\UploaderBundle\Naming\UniqidNamer
    eventtype:
      uri_prefix: /uploads/images/event-type
      upload_destination: '%kernel.project_dir%/public/uploads/images/event-type'
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
      namer:
        service: Vich\UploaderBundle\Naming\UniqidNamer
    activity:
      uri_prefix: /uploads/images/activity
      upload_destination: '%kernel.project_dir%/public/uploads/images/activity'
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
      namer:
        service: Vich\UploaderBundle\Naming\OrignameNamer
    exploit:
      uri_prefix: /uploads/images/exploit
      upload_destination: '%kernel.project_dir%/public/uploads/images/exploit'
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
      namer:
        service: Vich\UploaderBundle\Naming\UniqidNamer
    rsi_manufacturer:
      uri_prefix: /uploads/images/exploit
      upload_destination: '%kernel.project_dir%/public/uploads/images/rsi-manufacturer'
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
      namer:
        service: Vich\UploaderBundle\Naming\UniqidNamer
    rsi_ship:
      uri_prefix: /uploads/images/exploit
      upload_destination: '%kernel.project_dir%/public/uploads/images/rsi-ship'
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
      namer:
        service: Vich\UploaderBundle\Naming\UniqidNamer
